name: MeuPrimeirWorkflow

on:
  push:
    branches: 
      - 'main'
      - 'wip/*'
      - 'release/[0-9]+\.[0-9]+\.[0-9]+'
jobs:
  test_job:
    name: Executando job de teste
    runs-on: self-hosted
    steps:
    - name: Step 01
      uses: actions/checkout@v4
    - name: Step 02
      run: echo "Meu projeto YAML com a FIAP".
    - name: Step 03
      run: echo "Projeto de runner local".
    - name: Step 04
      run: echo "Usando windows".
